@startuml Game
actor "Game Organizer" as GO

participant "Game Flow" as GF
participant "Scoreboard" as SC

actor Player as PL
actor "Team Leader" as TL
participant "Device" as DV

group Launch [loop]
    GO -> GF : Initiate launch
    activate GF


    GF ->  DV : Trigger Tuning
    activate DV
    PL <-> DV : Tune
    activate PL
    
    alt Automatic Launch
        GF -> SC : Display Countdown
        activate SC
        DV -> DV : Countdown
    else Manual Launch
        GO -> GF : Force Launch
    end
    GF -> DV : Launch
    DV -> DV : Take Measurement
    deactivate SC
 
    DV -> PL : Display Measurement

    activate TL
    PL <-> TL : Discuss vote

    PL -> DV : Vote
    deactivate PL
    deactivate TL
    
    DV -> GF : Dispatch Vote
    deactivate DV

    GF -> SC : Update Vote Progress

    
    activate SC
    GF -> SC : Display Reconstruction

    GF-> SC : Update Score

    deactivate GF
    deactivate SC
end


@enduml