@startuml Game
actor "Game Organizer" as GO

participant "Game Flow" as GF
participant "Scoreboard" as SC

actor Player as PL
actor "Team Leader" as TL
participant "Device" as DV

activate GO

group Create Game
  GO -> GF : Open registrations
  activate GF
  activate DV
  activate PL
  PL -> DV : Wake up

  DV -> GF : Register Device

  deactivate PL
  deactivate DV

  GF -> GF : Update team data

  GO -> GF : Close registrations
  
end 

group Launch [loop]
    
    GO -> GF : Initiate launch

    GF ->  DV : Trigger Tuning
    activate DV
    PL <-> DV : Tune
    activate PL
    
    alt Automatic Launch
        GF -> SC : Display Countdown
        activate SC
        DV -> DV : Countdown
    else Manual Launch
        GO -> GF : Force Launch
    end
    deactivate GO
    GF -> DV : Launch
    DV -> DV : Take Measurement
    deactivate SC
 
    DV -> PL : Display Measurement

    activate TL
    PL <-> TL : Discuss vote

    PL -> DV : Vote
    deactivate PL
    deactivate TL
    
    DV -> GF : Dispatch Vote
    deactivate DV

    GF -> SC : Update Vote Progress

    
    activate SC
    GF -> SC : Display Reconstruction

    GF-> SC : Update Score

    deactivate GF
    deactivate SC
end


@enduml